// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: t71GRmRECWBzXEr1QZhGCg
// Component: b0oqErlnNeN
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: Pf6h4SzN-AG/component
import ProductCarousel from "../../ProductCarousel"; // plasmic-import: XMgD-f6dp3lx/component
import ProductCard from "../../ProductCard"; // plasmic-import: 0x0Vn3klYRuA/component
import Ratings from "../../Ratings"; // plasmic-import: c9aFkK1xl3br/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: CGmwQPHw__o/component
import BlogPost from "../../BlogPost"; // plasmic-import: m1pvFzYc5uNA/component
import Footer from "../../Footer"; // plasmic-import: WZZ6IGdRaeC/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: k_2fS8GEG_Hi/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: t71GRmRECWBzXEr1QZhGCg/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: b0oqErlnNeN/css

import arrivals17ZjsP3BvkJh from "./images/arrivals1.png"; // plasmic-import: 7zjsP_3bvkJh/picture
import arrivals2PmJollF7As from "./images/arrivals2.png"; // plasmic-import: pmJOLL-f7_As/picture
import arrivals3WCxYmsO42MmY from "./images/arrivals3.png"; // plasmic-import: wCxYmsO42mmY/picture
import arrivals4EYJoK4JBemXm from "./images/arrivals4.png"; // plasmic-import: eYJoK4JBemXM/picture
import arrivals5CXSeCRk0HfwN from "./images/arrivals5.png"; // plasmic-import: cXSeCRk0HfwN/picture
import arrivals6HrLMbKKcHBN from "./images/arrivals6.png"; // plasmic-import: HrLMbKKcH-bN/picture
import arrivals7KB7OJGkrR9Uk from "./images/arrivals7.png"; // plasmic-import: kB7oJGkrR9UK/picture
import arrivals8XnIwVWkm3TPf from "./images/arrivals8.png"; // plasmic-import: XNIwVWkm3tPf/picture
import f1PIq79SbpZz2D from "./images/f1.jpeg"; // plasmic-import: pIQ79sbpZz2D/picture
import f2IdQeYxqmaRRv from "./images/f2.jpeg"; // plasmic-import: IDQeYxqmaRRv/picture
import f3PiLfn9VmY6N from "./images/f3.jpeg"; // plasmic-import: PILfn-9vmY6N/picture
import f4Gr2KIzN7LoV from "./images/f4.jpeg"; // plasmic-import: gr2KIz-n7loV/picture
import b1VOcS18CuQrM from "./images/b1.jpeg"; // plasmic-import: vOcS_18CUQrM/picture
import b2D5JkJXqFhhv from "./images/b2.jpeg"; // plasmic-import: D5JK_jXqFHHV/picture
import b3RY3Ex7VxD8Se from "./images/b3.jpeg"; // plasmic-import: rY3EX7VxD8Se/picture
import adidasUwze5W3XgEh7 from "./images/adidas.png"; // plasmic-import: UWZE5w3xgEH7/picture
import hmRwMnoXvrjZiJ from "./images/hm.png"; // plasmic-import: RWMnoXvrjZiJ/picture
import kappaS3B4QamaAMnk from "./images/kappa.png"; // plasmic-import: S3b4QamaAMnk/picture
import lacosteZCt2JfnQcjWi from "./images/lacoste.png"; // plasmic-import: zCT2JFNQcjWi/picture
import levisLp7GoyQbXumZ from "./images/levis.png"; // plasmic-import: LP7GoyQbXumZ/picture

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  productCarousel?: p.Flex<typeof ProductCarousel>;
  featureItem?: p.Flex<typeof FeatureItem>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomeProps {
  className?: string;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  dataFetches?: PlasmicHome__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.freeBox__rHnTr)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__clZze)}
            >
              <div className={classNames(defaultcss.all, sty.freeBox__eqh9T)}>
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.freeBox__a1G2T)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__yhxSw
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___2GC0F)}
            >
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___3DiSf
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__pz5Q)}
                    src={arrivals17ZjsP3BvkJh}
                  />
                }
                onSale={"onSale" as const}
                price={"$65.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__b0BhV)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Chair"}
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___4Skj2
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__ae9K)}
                    src={arrivals2PmJollF7As}
                  />
                }
                onSale={"onSale" as const}
                price={"$80.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__jNv5E)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Single Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__tpcRg)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__pjBmw)}
                    src={arrivals3WCxYmsO42MmY}
                  />
                }
                price={"$40.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___4UlxO
                    )}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__y1Brr)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__qdhHh)}
                    src={arrivals4EYJoK4JBemXm}
                  />
                }
                onSale={"onSale" as const}
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__je9N7)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Stylish Chair"}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__gGa1P)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__p5Ysq)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__znBsk)}
                    src={arrivals5CXSeCRk0HfwN}
                  />
                }
                price={"$120.00"}
                title={"Modern Chair"}
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___1C0Qd
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__fOeq1)}
                    src={arrivals6HrLMbKKcHBN}
                  />
                }
                onSale={"onSale" as const}
                price={"$140.00"}
                title={"Mapple Wood Dinning Table"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__eENgp)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__a0Pa3)}
                    src={arrivals7KB7OJGkrR9Uk}
                  />
                }
                onSale={"onSale" as const}
                price={"$90.00"}
                title={"Arm Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__pjNvP)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__evaoh)}
                    src={arrivals8XnIwVWkm3TPf}
                  />
                }
                price={"$140.00"}
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__tVrEq
                    )}
                  >
                    {"Wooden Bed"}
                  </div>
                }
              />
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(defaultcss.all, sty.freeBox__ufveJ)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__ymMy1
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__exwJ0)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__mU10L)}
                price={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ycGnh
                    )}
                  >
                    {"$160.00"}
                  </div>
                }
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__cHbna)}
                    numReviews={"(12 Review)"}
                    stars={"two" as const}
                  />
                }
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xPd8M
                    )}
                  >
                    {"Designed Sofa"}
                  </div>
                }
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__pLVj)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__d7Fzl)}
                    src={f2IdQeYxqmaRRv}
                  />
                }
                price={"$200.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___1Dv5P
                    )}
                    stars={"four" as const}
                  />
                }
                title={"Dining Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__nmnkt)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__snKzr)}
                    src={f3PiLfn9VmY6N}
                  />
                }
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__fOmb)}
                    numReviews={"(23 Review)"}
                    stars={"five" as const}
                  />
                }
                title={"Chair and Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__yKVgQ)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__hslqf)}
                    src={f4Gr2KIzN7LoV}
                  />
                }
                price={"$299.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__tiBjC)}
                    numReviews={"(35 Review)"}
                  />
                }
                title={"Modern Arm Chair"}
                withReviews={"withReviews" as const}
              />
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.freeBox__tByqd)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__mwSkW
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__e7GtR)}
            >
              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__hw9Po)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__qwDni)}
                    src={b1VOcS18CuQrM}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__jIvi)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__gq7Z)}
                    src={b2D5JkJXqFhhv}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__viDhi)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___6Ybua)}
                    src={b3RY3Ex7VxD8Se}
                  />
                }
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___5Hr1)}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__pFaQ4)}
                src={adidasUwze5W3XgEh7}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___7I9Gn)}
                src={hmRwMnoXvrjZiJ}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__kg8Vp)}
                src={kappaS3B4QamaAMnk}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__k6MYg)}
                src={lacosteZCt2JfnQcjWi}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__yrqkj)}
                src={levisLp7GoyQbXumZ}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  productCarousel: typeof ProductCarousel;
  featureItem: typeof FeatureItem;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHome__Fetches;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
