// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: t71GRmRECWBzXEr1QZhGCg
// Component: c9aFkK1xl3br
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: t71GRmRECWBzXEr1QZhGCg/projectcss
import * as sty from "./PlasmicRatings.module.css"; // plasmic-import: c9aFkK1xl3br/css

import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: n4sO9ksARmXd/icon

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};

export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};

type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  dataFetches?: PlasmicRatings__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
        [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
        [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
        [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
        [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
        [sty.root__stars_zero]: hasVariant(variants, "stars", "zero")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___5RlBz, {
              [sty.svg__stars_five___5RlBzJs9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_zero___5RlBzE9Wvl]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__qCsSi, {
              [sty.svg__stars_five__qCsSiJs9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__qCsSIoRj79]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__qCsSIzelYw]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__qCsSi5V7Aq]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__qCsSIm1F]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__qCsSie9Wvl]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__cwnUo, {
              [sty.svg__stars_five__cwnUoJs9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__cwnUOoRj79]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__cwnUOzelYw]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__cwnUo5V7Aq]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__cwnUOm1F]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__cwnUoe9Wvl]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__tdgjO, {
              [sty.svg__stars_five__tdgjOJs9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__tdgjOoRj79]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__tdgjOzelYw]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__tdgjO5V7Aq]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__tdgjOm1F]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__tdgjOe9Wvl]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___8L5Y6, {
              [sty.svg__stars_five___8L5Y6Js9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four___8L5Y6ORj79]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one___8L5Y6ZelYw]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three___8L5Y65V7Aq]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two___8L5Y6M1F]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero___8L5Y6E9Wvl]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? true
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__nJRr, {
              [sty.svg__stars_five__nJRrJs9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__nJRroRj79]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__nJRrzelYw]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__nJRr5V7Aq]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__nJRrm1F]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__nJRrE9Wvl]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__hpM5, {
              [sty.svg__stars_five__hpM5Js9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__hpM5ORj79]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__hpM55V7Aq]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__hpM5M1F]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__qsLBc, {
              [sty.svg__stars_five__qsLBcJs9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__qsLBcoRj79]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__qsLBc5V7Aq]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__ayVXq, {
              [sty.svg__stars_five__ayVXqJs9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__ayVXqoRj79]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___8E2Rk, {
              [sty.svg__stars_five___8E2RkJs9Mv]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotNumReviews)
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRatings__VariantsArgs;
    args?: PlasmicRatings__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRatings__Fetches;
  } & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRatings__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
